version: "3.9"

services:
  server-prod:
    build:
      context: ./seenlive-server
      dockerfile: Dockerfile
      args:
        - customport=http://+:5000
        - customsslport=5001
      target: run-env-prod
    image: seenlive-server-prod
    environment:
      - seenlive-db-server
      - seenlive-db-username
      - seenlive-db-password
    ports: 
      - 5000:5000
      - 5001:5001

  client-prod:
    build:
      context: ./seenlive
      dockerfile: Dockerfile
      target: production
    image: seenlive-client-prod
    ports:
      - 3000:3000
      - 3001:3001
    depends_on: 
      - server-prod