version: "3.9"

services:
  server-prod:
    env_file:
      - .env
    environment:
      - seenlive-db-server=${DB_SERVER}
      - seenlive-db-username=${DB_USERNAME}
      - seenlive-db-password=${DB_PASSWORD}
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${KESTREL_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/aspnetapp.pfx
    build:
      context: ./seenlive-server
    container_name: seenlive-server-prod    
    ports: 
      - 5000:80
      - 5001:443
    volumes:
      - ~/.aspnet/https:/app/https # TODO retrieve certificate from GitHub secret
    networks:
      - seenlive_network

  client-prod:
    build:
      context: ./seenlive
    container_name: seenlive-client-prod
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - seenlive_network
    depends_on: 
      - server-prod
      
networks:
  seenlive_network:
    name: seenlive_network
    driver: bridge
    external: false