version: "3.9"

services:
  server-prod:
    build:
      context: ./seenlive-server
      dockerfile: Dockerfile
      target: build-env-prod
    image: seenlive-server-prod
    ports: 
      - 5000:5000
      - 5001:5001

  client-prod:
    build:
      context: ./seenlive
      dockerfile: Dockerfile
      target: production
    image: seenlive-client-prod
    ports:
      - 49160:3000
    depends_on: 
      - server-prod