name: .NET-Backend

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.101'
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
      working-directory: seenlive-server
    - name: Build
      run: dotnet build --no-restore
      working-directory: seenlive-server
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: seenlive-server
