name: .NET-Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
      working-directory: seenlive-server
    - name: Build
      run: dotnet build --no-restore
      working-directory: seenlive-server
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: seenlive-server
