name: Docker End-to-End Deployment

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose environment
        run: |
          echo "SEENLIVE_DB_SERVER=${{ secrets.SEENLIVEDBSERVERPROD }}" >> .env
          echo "SEENLIVE_DB_USERNAME=${{ secrets.SEENLIVEDBUSERNAMEPROD }}" >> .env
          echo "SEENLIVE_DB_PASSWORD=${{ secrets.SEENLIVEDBPASSWORDPROD }}" >> .env
          echo "KESTREL_PASSWORD=${{ secrets.KESTREL_PASSWORD }}" >> .env

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d
          
      # TODO